 
 ## training
 epochs: 20
 batch_size: 32
 learning_rate: 0.0001


 model_name: "VGG19", "inceptionv3","CNN1", "CNN2" 

 model_type: vgg19 ## path name for saving model
 augmentation: True
 continue_training: False
 masked: False
 processed: True

 seed: 123
 

 ## evaluation

 model_path: models/inceptionv3_aug/weights-01-0.79.hdf5